name: processor
environment:
  sdk: ^3.10.1
resolution: workspace
dependencies:
  json_annotation: ^4.9.0
  meta: ^1.15.0
dev_dependencies:
  build_runner: ^2.4.15
  gen_exporter: any
  json_serializable: ^6.9.4

