name: common_shared
environment:
  sdk: ^3.10.1
resolution: workspace
dependencies:
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
dev_dependencies:
  build_runner: ^2.4.15
  gen_exporter: any

