name: common_shared

environment:
  sdk: ^3.10.1
resolution: workspace

dependencies:
  #! Environment
  flutter_dotenv: ^5.2.1

  #! Localization
  intl: ^0.20.2

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  gen_exporter: any
