name: scripts

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  #! Modules
  common_tooling: any

  #! cli
  args: ^2.5.0

  #! File and Folders
  path: ^1.9.0
  yaml: ^3.1.2

  #! Dependency Injection
  get_it: ^8.0.3
