targets:
  $default:
    auto_apply_builders: false
    builders:
      #! Package Generators
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          include: ["lib/src/configs/**"]
      #! Module Generators
      gen_exporter|exporter:
        enabled: true
        options:
          folders:
            - annotations
            - configs
            - helpers
            - utils
