name: { { module_name } }

environment:
  sdk: ^3.10.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  processor: any
  core_presentation: any
  core_navigation: any
  common_shared: any
  common_presentation: any
  ui_foundation: any
  ui_components: any

  #! Navigation
  auto_route: ^10.1.0

  #! Dependency Injection
  injectable: ^2.5.0

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  gen_data: any
  gen_view_kit: any

  #? Dependency Injection
  injectable_generator: ^2.7.0
