name: core_navigation
environment:
  sdk: ^3.10.1
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0
  common_shared: any
  core_presentation: any
  processor: any
  ui_foundation: any
dev_dependencies:
  build_runner: ^2.4.15
  gen_data: any
  gen_exporter: any
  gen_view_kit: any

