name: foundation

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  processor: any

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  generator: any
