name: ui_foundation

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  gen_exporter: any

flutter:
  assets:
    - assets/icons/
