targets:
  $default:
    auto_apply_builders: false
    builders:
      #! Project Generators
      gen_exporter|exporter:
        enabled: true
        options:
          folders:
            - repository
            - usecase

global_options:
  gen_exporter|exporter:
    runs_before:
      - injectable_generator|injectable_builder
