name: demo_domain

environment:
  sdk: 3.9.0
resolution: workspace

dependencies:
  #! Modules
  core_domain: any

  #! Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  generator: any

  #? Dependency Injection
  injectable_generator: ^2.7.0
