name: {{module_name}}

environment:
  sdk: ^3.10.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  processor: any
  core_domain: any

  #! Dependency Injection
  injectable: ^2.5.2

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  gen_exporter: any
  gen_data: any

  #? Dependency Injection
  injectable_generator: ^2.7.0
