name: template
publish_to: none

environment:
  sdk: ^3.10.1

workspace:
  - app
  - tools/scripts
  - tools/processor
  #? Generator
  - tools/generator/core
  - tools/generator/plugins/assets
  - tools/generator/plugins/data
  - tools/generator/plugins/exporter
  - tools/generator/plugins/palette
  - tools/generator/plugins/view_kit
  #? Common
  - common/shared
  - common/presentation
  - tools/common
  #? Core
  - core/presentation
  - core/navigation
  - core/data
  - core/domain
  #? UiKit
  - uikit/foundation
  - uikit/components
  - uikit/previews
  #? Console
  - feature/global/feature/console/presentation
  #? Demo
  - feature/demo/domain
  - feature/demo/data
  - feature/demo/presentation

dev_dependencies:
  #? Analysis
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  default-flavor: prod
