name: template
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - app
  - processor
  - generator/core
  - generator/builder/data
  - generator/builder/exporter
  - generator/builder/palette
  - generator/builder/view_kit
  - common/shared
  - common/presentation
  - core/presentation
  - core/data
  - core/domain
  - feature/demo/domain
  - feature/demo/data
  - feature/demo/presentation
  - uikit/foundation

dev_dependencies:
  #? Analysis
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
