name: demo_presentation

environment:
  sdk: 3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  processor: any
  core_presentation: any
  core_data: any
  core_navigation: any
  demo_domain: any
  demo_data: any

  #! Navigation
  auto_route: ^10.1.0

  #! Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  gen_data: any
  gen_view_kit: any

  #? Dependency Injection
  injectable_generator: ^2.7.0
