name: demo_presentation

environment:
  sdk: 3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  processor: any
  core_presentation: any
  demo_domain: any
  demo_data: any

  #! Navigation
  auto_route: ^10.1.0

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Modules
  generator: any

  #? Navigation
  auto_route_generator: ^10.1.0
