targets:
  $default:
    auto_apply_builders: false
    builders:
      #! Project Generators
      gen_data|data:
        enabled: true
        generate_for:
          include:
            - "**/state.dart"
            - "**/source/**"
      gen_view_kit|view:
        enabled: true
        generate_for:
          include:
            - "**/view.dart"
      gen_view_kit|provider:
        enabled: true
        generate_for:
          include:
            - "**/provider.dart"
      gen_view_kit|view_model:
        enabled: true
        generate_for:
          include:
            - "**/view_model.dart"
        options:
          enable_cached_builds: true
      #! Dependency Injection
      injectable_generator|injectable_builder:
        enabled: true
        generate_for:
          include:
            - "lib/**"
      injectable_generator|injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - "lib/init.dart"

global_options:
  gen_view_kit|view:
    runs_before:
      - gen_view_kit|view_model
  gen_view_kit|provider:
    runs_before:
      - gen_view_kit|view_model
