targets:
  $default:
    builders:
      #! Project Generators
      gen_exporter|exporter:
        enabled: true
        options:
          folders:
            - entity
            - result
            - usecase
