name: common_presentation
environment:
  sdk: ^3.10.1
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  common_shared: any
dev_dependencies:
  build_runner: ^2.4.15
  gen_exporter: any

