name: app
description: "A template Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #! Modules
  #? Common
  common_shared: any
  common_presentation: any
  #? Core
  core_data: any
  core_presentation: any
  core_navigation: any
  #? UIKit
  ui_foundation: any
  ui_components: any
  #? Console
  console_presentation: any
  #? Demo
  demo_presentation: any

  #! Navigation
  auto_route: ^10.1.0

  #! Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  #! Localization
  intl: ^0.20.2

dev_dependencies:
  #! Generator
  build_runner: ^2.4.15

  #? Dependency Injection
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  default-flavor: prod

  assets:
    - .env.dev
    - .env.prod
